# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5a60507a5b9d8d118964b00d74e4ca2356467ab5297c5724a3f31ab0fb9a8bbef47109a035f0d90eb02cf9b07155b98e7f582d1425f57f0afef3e58d05a430

test:
  secret_key_base: 6d085dc168ff7b421be3c5644addc8f709181c61af762366f999a0f2289eaf866b0839061e884bdb63999697eaea2e0204e020075a0f5b98801d8ee51e3bb461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
